import { Theme } from '@mui/material/styles'

export const typography: Theme['typography'] = {
  h1: {
    fontFamily: 'Poppins',
    fontSize: '52px',
    fontWeight: '500',
    lineHeight: '64px',
    fontStyle: 'normal',
  },
  h2: {
    fontFamily: 'Poppins',
    fontSize: '40px',
    fontWeight: '500',
    lineHeight: '48px',
    fontStyle: 'normal',
  },
  h3: {
    fontFamily: 'Poppins',
    fontSize: '36px',
    fontWeight: '500',
    lineHeight: '48px',
    fontStyle: 'normal',
  },
  h4: {
    fontFamily: 'Poppins',
    fontSize: '24px',
    fontWeight: '500',
    lineHeight: '28px',
    fontStyle: 'normal',
  },
  h5: {
    fontFamily: 'Poppins',
    fontSize: '18px',
    fontWeight: '600',
    lineHeight: '28px',
    fontStyle: 'normal',
  },
  h6: {
    fontFamily: 'Inter',
    fontWeight: '600',
    fontSize: '17px',
    lineHeight: '24px',
    fontStyle: 'normal',
  },
  button: {
    fontFamily: 'Inter',
    fontWeight: '600',
    fontSize: '15px',
    lineHeight: '24px',
    fontStyle: 'normal',
  },
  links: {
    fontFamily: 'Inter',
    fontWeight: '500',
    fontSize: '15px',
    lineHeight: '24px',
    fontStyle: 'normal',
  },
  caption1: {
    fontFamily: 'Inter',
    fontWeight: '600',
    fontSize: '15px',
    lineHeight: '20px',
    fontStyle: 'normal',
  },
  caption2: {
    fontFamily: 'Inter',
    fontWeight: '600',
    fontSize: '13px',
    lineHeight: '20px',
    fontStyle: 'normal',
  },
  label: {
    fontFamily: 'Inter',
    fontWeight: '600',
    fontSize: '14px',
    lineHeight: '24px',
    fontStyle: 'normal',
  },
  body1: {
    fontFamily: 'Inter',
    fontWeight: '400',
    fontSize: '16px',
    lineHeight: '24px',
    fontStyle: 'normal',
  },
  body2: {
    fontFamily: 'Inter',
    fontWeight: '400',
    fontSize: '14px',
    lineHeight: '20px',
    fontStyle: 'normal',
  },
  overline: {
    fontFamily: 'Inter',
    fontWeight: '400',
    fontSize: '12px',
    lineHeight: '20px',
    fontStyle: 'normal',
  },
  num_l: {
    fontFamily: 'Poppins',
    fontWeight: '600',
    fontSize: '22px',
    lineHeight: '24px',
    fontStyle: 'normal',
  },
  num_s: {
    fontFamily: 'Poppins',
    fontWeight: '600',
    fontSize: '16px',
    lineHeight: '24px',
    fontStyle: 'normal',
  },
}
